# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Curiosity-Station-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Particle-SDK'
  pod 'ParticleSetup'
  # Pods for Curiosity-Station-iOS

end
